# Generated by Django 5.2.3 on 2025-06-26 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('VIRTUAL_ACCOUNT', 'Virtual Account'), ('EWALLET', 'E-Wallet'), ('RETAIL_OUTLET', 'Retail Outlet'), ('CREDIT_CARD', 'Credit Card'), ('QR_CODE', 'QR Code')], max_length=20)),
                ('icon', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1_month', '1 Bulan'), ('3_month', '3 Bulan'), ('6_month', '6 Bulan')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField()),
                ('features', models.JSONField(default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('badge', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('xendit_invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('description', models.TextField()),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('success_redirect_url', models.URLField(blank=True, null=True)),
                ('failure_redirect_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
