# Generated by Django 5.2.3 on 2025-06-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('1 Bulan', '1 Bulan'), ('3 Bulan', '3 Bulan'), ('6 Bulan', '6 Bulan')], max_length=50, unique=True),
        ),
    ]
